### ISSUE TITLE
Python client issue with _key

### ISSUE THREAD

**Issue by AstroChelonian** [terminusdb/terminusdb-client-python#239]
I run the  script example.py from here  https://github.com/terminusdb-labs/terminusdb-seshat/tree/main/seshat_walkthough
The class Polity(DocumentTemplate) has a lexical key :_key  = LexicalKey("polid").

I select to run the script with the _key  = LexicalKey("polid") (key as a string) and I get the following error:

```
/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlclient/woqlClient.py:630: UserWarning: Delete Database Warning: You have not specify the team, assuming PAOK-test/test_seshat
  warnings.warn(
/home/astrochelonian/.local/lib/python3.8/site-packages/numpydoc/docscrape.py:418: UserWarning: Unknown section Attribute
  warn(msg)
Traceback (most recent call last):
  File "example.py", line 255, in <module>
    afdurn = Polity(polid='af_durn', originalID='Afdurrn',
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlschema/woql_schema.py", line 154, in init
    obj._id = obj._key.idgen(obj)
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlschema/woql_schema.py", line 67, in idgen
    prefix, key_list = self._idgen_prep(obj)
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlschema/woql_schema.py", line 33, in _idgen_prep
    raise ValueError(f"Cannot get {item} from {obj}")
ValueError: Cannot get p from <__main__.Polity object at 0x7fb515ce43d0>
```

If I I select to run the script with the _key  = LexicalKey(["polid"]) (key as a list)  I get the following error:

```
/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlclient/woqlClient.py:630: UserWarning: Delete Database Warning: You have not specify the team, assuming PAOK-test/test_seshat
  warnings.warn(
/home/astrochelonian/.local/lib/python3.8/site-packages/numpydoc/docscrape.py:418: UserWarning: Unknown section Attribute
  warn(msg)
Traceback (most recent call last):
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlschema/woql_schema.py", line 106, in _check_missing_prop
    check_type(str(None), None, prop_type)
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/typeguard/__init__.py", line 688, in check_type
    raise TypeError(
TypeError: type of None must be bool; got NoneType instead

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "example.py", line 261, in <module>
    client.insert_document(afdurn, commit_msg=f"Inserting data")
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlclient/woqlClient.py", line 1018, in insert_document
    document = self._conv_to_dict(document)
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlclient/woqlClient.py", line 965, in _conv_to_dict
    return obj._obj_to_dict()
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlschema/woql_schema.py", line 250, in _obj_to_dict
    result[item] = the_item._embeded_rep()
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlschema/woql_schema.py", line 231, in _embeded_rep
    return self._obj_to_dict()
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlschema/woql_schema.py", line 237, in _obj_to_dict
    _check_missing_prop(self)
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/terminusdb_client/woqlschema/woql_schema.py", line 112, in _check_missing_prop
    check_type(prop, prop_value, prop_type)
  File "/home/astrochelonian/.local/lib/python3.8/site-packages/typeguard/__init__.py", line 688, in check_type
    raise TypeError(
TypeError: type of unknown must be bool; got NoneType instead

```

**Comment by Cheukting** [comment]
The error handling is not very good but it is because the objects are missing the properties. If the properties can be missing you can make it Optional in defining the schema. For the keys, it should accepting a list or a string in the next patch.
